---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
- listen: reconfigure networking
  name: disable network manager
  systemd:
    daemon_reload: yes
    enabled: no
    masked: yes
    name: NetworkManager
- listen: reconfigure networking
  name: enable systemd-networkd
  systemd:
    daemon_reload: yes
    enabled: yes
    masked: no
    name: systemd-networkd
- listen: reconfigure networking
  reboot:
